export type ExcelAccountAll = {
  TVCONO: number;
  TVDIVI: string;
  TVYEA4: number;
  TVSUNO: string;
  TVSINO: string;
  TVTXNO: string;
  TVACAM: number;
  TVVTAM: number;
  TVVTCD: number;
  TVVTP1: string;
  TVCUCD: string;
  TVIVDT: number;
  TVACDT: number;
  TVVONO: number;
  TVSPYN: string;
  TVSUNM: string;
  TVADR1: string;
  TVRGDT: number;
  TVRGTM: number;
  TVLMDT: number;
  TVCHNO: number;
  TVCHID: string;
  TVAIT2: string;
  TVVRNO: string;
  TVVSEQ: string;
  TVREM1: string;
  TVREM2: string;
};

export type AccountFromExcel = {
  TaxInvoiceDate: date;
  AccountingEntryDate: date;
  TaxID: string;
  MerchantName: string;
  Location: string;
  BranchNumber: string;
  InvoiceNo: string;
  ExcludeVATAmount: number;
  voucherNumber: number;
  VATAmount: string;
  VoucherNumber: string;
  VATBranch: string;
};